AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: focused-api

Parameters:
  SidecarEnv:
    Type: String
    Default: local
    AllowedValues:
      - local
      - dev
      - staging
      - prod
  GitHubAppID:
    Type: String
  GitHubAppPrivateKey:
    Type: String

Globals:
  Function:
    Timeout: 5
    Environment:
      Variables:
        SIDECAR_ENV: !Ref SidecarEnv
        GITHUB_APP_ID: !Ref GitHubAppID
        GITHUB_APP_PRIVATE_KEY: !Ref GitHubAppPrivateKey

Resources:
  HealthCheck:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: rust-cargolambda
      BuildProperties:
        Binary: healthcheck
    Properties:
      CodeUri: ./lambda
      Handler: bootstrap
      Runtime: provided.al2
      Events:
        HTTPEvent:
          Type: "HttpApi"
          Properties:
            Path: "/ok"
            Method: "GET"
