[package]
name = "test-handler"
version = "0.1.0"
edition = "2021"

[dependencies]
lambda_runtime = "0.8.2"
serde = "1.0.189"
tokio = { version = "1", features = ["macros"] }
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = { version = "0.3", default-features = false, features = ["fmt"] }

# standard crate data is left out
[dev-dependencies]
cargo-llvm-cov = ">= 0.5.33"

[[bin]]
name = "healthcheck"
path = "src/healthcheck.rs"

[[bin]]
name = "whoami"
path = "src/whoami.rs"
